export namespace ease {
    function easeLinear(value: any): any;
    function easeInQuad(value: any): number;
    function easeOutQuad(value: any): number;
    function easeInOutQuad(value: any): number;
    function easeInCubic(value: any): number;
    function easeOutCubic(value: any): number;
    function easeInOutCubic(value: any): number;
    function easeInQuart(value: any): number;
    function easeOutQuart(value: any): number;
    function easeInOutQuart(value: any): number;
    function easeInSine(value: any): number;
    function easeOutSine(value: any): number;
    function easeInOutSine(value: any): number;
    function easeInExpo(value: any): number;
    function easeOutExpo(value: any): number;
    function easeInOutExpo(value: any): number;
    function easeInCirc(value: any): number;
    function easeOutCirc(value: any): number;
    function easeInOutCirc(value: any): number;
    function easeInBack(value: any): number;
    function easeOutBack(value: any): number;
    function easeInOutBack(value: any): number;
}
export function easeLinear(value: any): any;
export function easeInQuad(value: any): number;
export function easeOutQuad(value: any): number;
export function easeInOutQuad(value: any): number;
export function easeInCubic(value: any): number;
export function easeOutCubic(value: any): number;
export function easeInOutCubic(value: any): number;
export function easeInQuart(value: any): number;
export function easeOutQuart(value: any): number;
export function easeInOutQuart(value: any): number;
export function easeInSine(value: any): number;
export function easeOutSine(value: any): number;
export function easeInOutSine(value: any): number;
export function easeInExpo(value: any): number;
export function easeOutExpo(value: any): number;
export function easeInOutExpo(value: any): number;
export function easeInCirc(value: any): number;
export function easeOutCirc(value: any): number;
export function easeInOutCirc(value: any): number;
export function easeInBack(value: any): number;
export function easeOutBack(value: any): number;
export function easeInOutBack(value: any): number;
export function setEasingByName(easeName: any): any;
export function getEasingByName(name: any): any;
//# sourceMappingURL=index.d.ts.map